from typing import Protocol, Optional
from uuid import UUID

from fast_api_template.modules.user.repository.schemas.edit_user_schema import EditUserSchema
from fast_api_template.modules.user.repository.schemas.create_user_schema import (
    CreateUserSchema,
)
from fast_api_template.modules.user.user import User


class UserRepositoryContract(Protocol):
    async def create(self, create_user_schema: CreateUserSchema) -> User: ...
    async def get_with_email(self, email: str) -> User: ...
    async def delete(self, user_pid: UUID) -> None: ...
    async def edit(self, user_id: int, partial_user: EditUserSchema) -> User: ...
    async def get_with_stripe_id(self, stripe_id: str) -> User: ...
    async def set_user_subscription_plan(self, user_id: int, subscription_plan_id: Optional[int]) -> None: ...